<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CCast/CCastProto.proto

namespace Chromecast;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>symcon.ccast.CCastMessage</code>
 */
class CCastMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 protocol_version = 1;</code>
     */
    protected $protocol_version = null;
    /**
     * Generated from protobuf field <code>string SourceId = 2;</code>
     */
    protected $SourceId = '';
    /**
     * Generated from protobuf field <code>string ReceiverId = 3;</code>
     */
    protected $ReceiverId = '';
    /**
     * Generated from protobuf field <code>string Urn = 4;</code>
     */
    protected $Urn = '';
    /**
     * Generated from protobuf field <code>optional int32 PayloadType = 5;</code>
     */
    protected $PayloadType = null;
    /**
     * Generated from protobuf field <code>string Payload = 6;</code>
     */
    protected $Payload = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $protocol_version
     *     @type string $SourceId
     *     @type string $ReceiverId
     *     @type string $Urn
     *     @type int $PayloadType
     *     @type string $Payload
     * }
     */
    public function __construct($data = null)
    {
        \Chromecast\CCastProto::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 protocol_version = 1;</code>
     * @return int
     */
    public function getProtocolVersion()
    {
        return isset($this->protocol_version) ? $this->protocol_version : 0;
    }

    public function hasProtocolVersion()
    {
        return isset($this->protocol_version);
    }

    public function clearProtocolVersion()
    {
        unset($this->protocol_version);
    }

    /**
     * Generated from protobuf field <code>optional int32 protocol_version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProtocolVersion(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->protocol_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SourceId = 2;</code>
     * @return string
     */
    public function getSourceId()
    {
        return $this->SourceId;
    }

    /**
     * Generated from protobuf field <code>string SourceId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->SourceId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ReceiverId = 3;</code>
     * @return string
     */
    public function getReceiverId()
    {
        return $this->ReceiverId;
    }

    /**
     * Generated from protobuf field <code>string ReceiverId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiverId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->ReceiverId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Urn = 4;</code>
     * @return string
     */
    public function getUrn()
    {
        return $this->Urn;
    }

    /**
     * Generated from protobuf field <code>string Urn = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUrn(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->Urn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 PayloadType = 5;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return isset($this->PayloadType) ? $this->PayloadType : 0;
    }

    public function hasPayloadType()
    {
        return isset($this->PayloadType);
    }

    public function clearPayloadType()
    {
        unset($this->PayloadType);
    }

    /**
     * Generated from protobuf field <code>optional int32 PayloadType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->PayloadType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Payload = 6;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->Payload;
    }

    /**
     * Generated from protobuf field <code>string Payload = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->Payload = $var;

        return $this;
    }

}

