<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CCast/CCastProto.proto

namespace Chromecast;

class CCastProto
{
    public static bool $is_initialized = false;

    public static function initOnce(): void
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xFD\x01\x0A\x16CCast/CCastProto.proto\x12\x0Csymcon.ccast\"\xB0\x01\x0A\x0CCCastMessage\x12\x1D\x0A\x10protocol_version\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x10\x0A\x08SourceId\x18\x02 \x01(\x09\x12\x12\x0A\x0AReceiverId\x18\x03 \x01(\x09\x12\x0B\x0A\x03Urn\x18\x04 \x01(\x09\x12\x18\x0A\x0BPayloadType\x18\x05 \x01(\x05H\x01\x88\x01\x01\x12\x0F\x0A\x07Payload\x18\x06 \x01(\x09B\x13\x0A\x11_protocol_versionB\x0E\x0A\x0C_PayloadTypeB\x1A\xCA\x02\x0AChromecast\xE2\x02\x0AChromecastb\x06proto3",
            true
        );

        static::$is_initialized = true;
    }
}

