<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CCast/CCastProto.proto

namespace Chromecast;

class CCastProto
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
Œ
CCast/CCastProto.protosymcon.ccast"Å
CCastMessage
protocol_version (
SourceId (	

ReceiverId (	
Urn (	
PayloadType (
Payload (	B 
Chromecast‚
Chromecastbproto3',
            true
        );

        static::$is_initialized = true;
    }
}

